import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Project Farmers</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
               

                

                <div className={styles.grid}>
                    <a href="/home" className={styles.card}>
                        <h2>FARMER'S LOGIN &rarr;</h2>
                        <p>Farmers most dedicating and hardworking people of Nation.</p>
                    </a>

                    <a href="/home" className={styles.card}>
                        <h2>USER'S LOGIN&rarr;</h2>
                        <p>The customer’s perception is your reality.</p>
                    </a>

                    
                </div>
            </main>

            
        </div>
    );
};

export default Home;
