import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { AuthenticationForm } from "../components";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Project Farmers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthenticationForm />
    </div>
  );
};

export default Home;

