import type { NextPage } from "next";
import Head from "next/head";
import React from "react";

import Orders from "../components/orders";

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Orders</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="stylesheet" id="bootstrap-css" href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" />
                <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

                <link rel="stylesheet" href="/styles/profile.css" />
                <link rel="stylesheet" href="/styles/orders.css" />
                <link rel="stylesheet" href="/styles/nav.css" />
            </Head>
            <Orders />
        </>
    );
};

export default Home;