import type { NextPage } from "next";
import Head from "next/head";
import React from "react";

import data from "../components/data";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Orders</title>
				<meta name="description" content="Generated by create next app" />
				<link
					rel="stylesheet"
					id="bootstrap-css"
					href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
				/>
				<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
				<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

				<link rel="stylesheet" href="/styles/profile.css" />
				<link rel="stylesheet" href="/styles/orders.css" />
				<link rel="stylesheet" href="/styles/nav.css" />
			</Head>
			<div>
				<div id="abc">
					<nav>
						<ul>
							<li>
								<a href="/profile/dashboard">Home</a>
							</li>
							<li>
								<a href="/profile">View Profile</a>
							</li>
							<li>
								<a href="/addcrops">Add crops</a>
							</li>
							<li>
								<a href="/orders">Orders</a>
							</li>
							<li>
								<a href="/">Logout</a>
							</li>
						</ul>
					</nav>
				</div>
				<div className="orderBox">
					{data.map((dat) => {
						const { img, cropName, price } = dat;
						return (
							<div className="order" style={{ marginLeft: 5, marginRight: 5 }}>
								<img src={img} alt=""></img>
								<h1>{cropName}</h1>
								<h4>{price}</h4>
							</div>
						);
					})}
				</div>
			</div>
		</>
	);
};

export default Home;
