import { AppShell, Header, Navbar } from "@mantine/core";
import type { NextPage } from "next";
import Head from "next/head";
import React from "react";

import data from "../components/data";
import HeaderMenuColored from "../components/NavHeader";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Orders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="/styles/profile.css" />
        <link rel="stylesheet" href="/styles/orders.css" />
        <link rel="stylesheet" href="/styles/nav.css" />
      </Head>
      <AppShell padding={0} header={<HeaderMenuColored />}>
        <div className="orderBox">
          {data.map((dat) => {
            const { img, cropName, price } = dat;
            return (
              <div className="order" style={{ marginLeft: 5, marginRight: 5 }}>
                <img src={img} alt=""></img>
                <h1>{cropName}</h1>
                <h4>{price}</h4>
              </div>
            );
          })}
        </div>
      </AppShell>
    </>
  );
};

export default Home;
