import type { NextPage } from "next";
import React from "react";
import SignUp from "../components/signup" 
import Head from "next/head";
const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Registration Page</title>
                <meta name="description" content="Generated by create next app" />
                
                <link rel="stylesheet" href="/styles/login.css" />
            </Head>
            <SignUp />
        </>
    )
};

export default Home;