import type { NextPage } from "next";
import React from "react";
import Profile from "../../components/profile" 
import Head from "next/head";
const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Profile</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="stylesheet" id="bootstrap-css" href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" />
                <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
                <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

                <link rel="stylesheet" href="/styles/profile.css" />
                <link rel="stylesheet" href="/styles/nav.css" />
            </Head>
            <Profile />
        </>
    )
};

export default Home;
