import type { NextPage } from "next";
import Head from "next/head";
import React from "react";

import Dashboard from "../../components/dashboard";
const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Dashboard</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="stylesheet" href="/https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" />
				<link rel="stylesheet" href="/styles/dashboard.css" />
			</Head>
			<Dashboard />
		</>
	);
};

export default Home;
